#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStore
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CSR")]
	public partial class DataClassesCSRDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataClassesCSRDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["CSRConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesCSRDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesCSRDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesCSRDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesCSRDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spPROCESS_TRANSACTION")]
		public int spPROCESS_TRANSACTION(
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string request_mode, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> request_id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string status_symbol, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string category_symbol, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string issue_symbol, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> profile_index, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(8000)")] string subject, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(8000)")] string service_address, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string request, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string resolution, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GWP_Account_Number", DbType="VarChar(255)")] string gWP_Account_Number, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="GWP_Issue", DbType="VarChar(8000)")] string gWP_Issue, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(8000)")] string location_address, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string description, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> date_needed_by, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string submitted_by_ip_address, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Bit")] System.Nullable<bool> submitted_by_IsContactAllowed, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(8000)")] string submitted_by_request_script_name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string submitted_by_full_name, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(255)")] string submitted_by_email_address, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(120)")] string submitted_by_phone, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Text")] string comments, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string code_id, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> intOUPUT_RequestID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> intOUTPUT_TransactionID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="IsEnrollmentRequest", DbType="Bit")] System.Nullable<bool> isEnrollmentRequest)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), request_mode, request_id, status_symbol, category_symbol, issue_symbol, profile_index, subject, service_address, request, resolution, gWP_Account_Number, gWP_Issue, location_address, description, date_needed_by, submitted_by_ip_address, submitted_by_IsContactAllowed, submitted_by_request_script_name, submitted_by_full_name, submitted_by_email_address, submitted_by_phone, comments, code_id, intOUPUT_RequestID, intOUTPUT_TransactionID, isEnrollmentRequest);
			intOUPUT_RequestID = ((System.Nullable<int>)(result.GetParameterValue(23)));
			intOUTPUT_TransactionID = ((System.Nullable<int>)(result.GetParameterValue(24)));
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
